[tool.poetry]
name = "fastfetchbot"
version = "0.1.0"
description = ""
authors = ["Zhen Zhong <auroradysis@gmail.com>", "Jichen Jiang <enturreopy@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.99.0"
python-telegram-bot = "^20.3"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
